language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - easy_install vsc-install
script:
  # 'hpcugent' is a mandatory remote for setup.py to work (because of vsc-install)
  - git remote add hpcugent https://github.com/hpcugent/vsc-base.git
  # only run part of the tests with Python 3 for now (until whole code base is Py3 compatible)
  - if [ "$(echo $TRAVIS_PYTHON_VERSION | cut -f1 -d.)" == '3' ]; then
        python setup.py test -F 'dateandtime';
    else
        python setup.py test;
    fi;
